-- Finance Brain · S1.1 · Estrutura real (entidades, caixas, listas do CdG)
-- Gerado a partir da BD_Dropdowns_MasterFile.xlsx (SharePoint, versão de 5 set 2026) com as correções de 29 set:
--   Setubal com os CC de um centro TUMO; Tondela nos Produtos do Shaken Futures; General Coimbra retirado;
--   External_Programs_Ops → Shaken_Future_Ops no Shaken_Futures_2627; produto "AI DIVE" uniformizado para "AI Dive".
-- Pode correr nos dois ambientes (testes e produção). Não tem dados pessoais.
begin;

insert into public.entidades (codigo,nome_legal,tipo,pais,nif,moeda,forma_obrigar) values
  ('TOP','Associação Topsail','Associação','PT','516657364','EUR','FM + PSC, em conjunto'),
  ('101010','Associação 101010 Portugal','Associação','PT','515722812','EUR','FM + PSC, em conjunto'),
  ('ACAD','Shaken Academy, Unipessoal Lda','Sociedade por quotas','PT','519187261','EUR','FM + PSC, em conjunto'),
  ('SNS','Shaken Not Stirred, Lda','Sociedade por quotas','PT','515309338','EUR','PSC (um gerente)'),
  ('ES','Shaken Not Stirred Ventures Spain, SL','Sociedad Limitada','ES','B88676218','EUR','FM + PSC, em conjunto');
insert into public.caixas_faturas (email,descricao) values
  ('admin@tumo.pt','TUMO'),
  ('admin@42lisboa.com','42'),
  ('admin@shakenacademy.pt','Shaken Academy'),
  ('admin@tumo.es','TUMO Espanha'),
  ('admin@shakenfutures.pt','Shaken Futures (faturas da 101010, Topsail ou Academy)'),
  ('admin@shaken.pt','Shaken');

insert into public.cdg_bu (codigo,familia,epoca,ativo,notas) values
  ('Shared_Services_26','Shared_Services','2026',true,null),
  ('School_42_26','School_42','2026',true,null),
  ('TUMO_2526','TUMO','2025/26',false,'Época 2025/26 encerrada: inativa. Reativar se ainda entrarem documentos desta época'),
  ('TUMO_2627','TUMO','2026/27',true,null),
  ('Professional_Programs_26','Professional_Programs','2026',true,null),
  ('Consulting_Programs_26','Consulting_Programs','2026',true,null),
  ('External_Programs_2526','Shaken_Futures','2025/26',false,'Nome antigo do Shaken Futures (família a confirmar). Época 2025/26 encerrada: inativa. Reativar se ainda entrarem documentos desta época'),
  ('Shaken_Futures_2627','Shaken_Futures','2026/27',true,null),
  ('International_2526','International','2025/26',false,'Época 2025/26 encerrada: inativa. Reativar se ainda entrarem documentos desta época'),
  ('International_2627','International','2026/27',true,null),
  ('Ignore','Ignore',null,false,null),
  ('Shared_Services_2526','Shared_Services','2025/26',false,'Época 2025/26 encerrada: inativa. Reativar se ainda entrarem documentos desta época');
insert into public.cdg_entidade_bu (entidade_id,bu)
select e.id, v.bu from (values
  ('519187261','Shared_Services_26'),
  ('519187261','School_42_26'),
  ('519187261','TUMO_2526'),
  ('519187261','TUMO_2627'),
  ('519187261','Professional_Programs_26'),
  ('519187261','Consulting_Programs_26'),
  ('519187261','External_Programs_2526'),
  ('519187261','Shaken_Futures_2627'),
  ('519187261','International_2526'),
  ('519187261','International_2627'),
  ('519187261','Ignore'),
  ('516657364','Shared_Services_26'),
  ('516657364','School_42_26'),
  ('516657364','TUMO_2526'),
  ('516657364','TUMO_2627'),
  ('516657364','Professional_Programs_26'),
  ('516657364','Consulting_Programs_26'),
  ('516657364','External_Programs_2526'),
  ('516657364','Shaken_Futures_2627'),
  ('516657364','International_2526'),
  ('516657364','International_2627'),
  ('516657364','Ignore'),
  ('515722812','Shared_Services_26'),
  ('515722812','School_42_26'),
  ('515722812','TUMO_2526'),
  ('515722812','TUMO_2627'),
  ('515722812','Professional_Programs_26'),
  ('515722812','Consulting_Programs_26'),
  ('515722812','External_Programs_2526'),
  ('515722812','Shaken_Futures_2627'),
  ('515722812','International_2526'),
  ('515722812','International_2627'),
  ('515722812','Ignore'),
  ('515309338','Shared_Services_26'),
  ('515309338','School_42_26'),
  ('515309338','TUMO_2526'),
  ('515309338','TUMO_2627'),
  ('515309338','Professional_Programs_26'),
  ('515309338','Consulting_Programs_26'),
  ('515309338','External_Programs_2526'),
  ('515309338','Shaken_Futures_2627'),
  ('515309338','International_2526'),
  ('515309338','International_2627'),
  ('515309338','Ignore'),
  ('B88676218','Shared_Services_26'),
  ('B88676218','School_42_26'),
  ('B88676218','TUMO_2526'),
  ('B88676218','TUMO_2627'),
  ('B88676218','Professional_Programs_26'),
  ('B88676218','Consulting_Programs_26'),
  ('B88676218','External_Programs_2526'),
  ('B88676218','Shaken_Futures_2627'),
  ('B88676218','International_2526'),
  ('B88676218','International_2627'),
  ('B88676218','Ignore')
) as v(nif,bu) join public.entidades e on e.nif = v.nif;
insert into public.cdg_produto (bu,produto) values
  ('Consulting_Programs_26','General'),
  ('External_Programs_2526','British Council'),
  ('External_Programs_2526','Evora'),
  ('External_Programs_2526','Experience AI'),
  ('External_Programs_2526','General'),
  ('External_Programs_2526','Intercambios Piaui'),
  ('External_Programs_2526','TASIS'),
  ('External_Programs_2526','TASIS Community Program'),
  ('External_Programs_2526','Taster Programs'),
  ('External_Programs_2526','Tondela'),
  ('Shaken_Futures_2627','General'),
  ('Shaken_Futures_2627','British Council'),
  ('Shaken_Futures_2627','Evora'),
  ('Shaken_Futures_2627','Intercambios Piaui'),
  ('Shaken_Futures_2627','Taster Programs'),
  ('Ignore','Ignore'),
  ('International_2526','General'),
  ('International_2627','General'),
  ('Professional_Programs_26','AI Dive'),
  ('Professional_Programs_26','General'),
  ('Professional_Programs_26','General Lisboa'),
  ('Professional_Programs_26','General Porto'),
  ('Professional_Programs_26','Step Up'),
  ('School_42_26','General'),
  ('School_42_26','Lisboa'),
  ('School_42_26','Porto'),
  ('School_42_26','SEA:ME'),
  ('Shared_Services_2526','General'),
  ('Shared_Services_26','General'),
  ('TUMO_2526','Bilbao'),
  ('TUMO_2526','Coimbra'),
  ('TUMO_2526','Espanha'),
  ('TUMO_2526','General'),
  ('TUMO_2526','Lisboa'),
  ('TUMO_2526','Porto'),
  ('TUMO_2526','Portugal'),
  ('TUMO_2627','Bilbao'),
  ('TUMO_2627','Coimbra'),
  ('TUMO_2627','Espanha'),
  ('TUMO_2627','General'),
  ('TUMO_2627','Lisboa'),
  ('TUMO_2627','Porto'),
  ('TUMO_2627','Portugal'),
  ('TUMO_2627','Setubal'),
  ('Shaken_Futures_2627','Tondela');
insert into public.cdg_cc (bu,produto,cc) values
  ('Consulting_Programs_26','General','Consulting_Programs_Ops'),
  ('Consulting_Programs_26','General','Income_Sources'),
  ('External_Programs_2526','British Council','External_Programs_Ops'),
  ('External_Programs_2526','British Council','Facilities_and_IT'),
  ('External_Programs_2526','British Council','Income_Sources'),
  ('External_Programs_2526','Evora','External_Programs_Ops'),
  ('External_Programs_2526','Evora','Facilities_and_IT'),
  ('External_Programs_2526','Evora','Finance_and_Legal'),
  ('External_Programs_2526','Evora','Income_Sources'),
  ('External_Programs_2526','Experience AI','External_Programs_Ops'),
  ('External_Programs_2526','Experience AI','Income_Sources'),
  ('External_Programs_2526','General','External_Programs_Ops'),
  ('External_Programs_2526','General','Income_Sources'),
  ('External_Programs_2526','Intercambios Piaui','External_Programs_Ops'),
  ('External_Programs_2526','Intercambios Piaui','Facilities_and_IT'),
  ('External_Programs_2526','Intercambios Piaui','Income_Sources'),
  ('External_Programs_2526','TASIS','External_Programs_Ops'),
  ('External_Programs_2526','TASIS','Facilities_and_IT'),
  ('External_Programs_2526','TASIS','Income_Sources'),
  ('External_Programs_2526','TASIS Community Program','External_Programs_Ops'),
  ('External_Programs_2526','TASIS Community Program','Facilities_and_IT'),
  ('External_Programs_2526','TASIS Community Program','Income_Sources'),
  ('External_Programs_2526','Taster Programs','External_Programs_Ops'),
  ('External_Programs_2526','Taster Programs','Income_Sources'),
  ('External_Programs_2526','Tondela','External_Programs_Ops'),
  ('External_Programs_2526','Tondela','Facilities_and_IT'),
  ('External_Programs_2526','Tondela','Finance_and_Legal'),
  ('External_Programs_2526','Tondela','Income_Sources'),
  ('Shaken_Futures_2627','British Council','Shaken_Future_Ops'),
  ('Shaken_Futures_2627','British Council','Facilities_and_IT'),
  ('Shaken_Futures_2627','British Council','Income_Sources'),
  ('Shaken_Futures_2627','Evora','Shaken_Future_Ops'),
  ('Shaken_Futures_2627','Evora','Facilities_and_IT'),
  ('Shaken_Futures_2627','Evora','Finance_and_Legal'),
  ('Shaken_Futures_2627','Evora','Income_Sources'),
  ('Shaken_Futures_2627','General','Shaken_Future_Ops'),
  ('Shaken_Futures_2627','General','Income_Sources'),
  ('Shaken_Futures_2627','Intercambios Piaui','Shaken_Future_Ops'),
  ('Shaken_Futures_2627','Intercambios Piaui','Facilities_and_IT'),
  ('Shaken_Futures_2627','Intercambios Piaui','Income_Sources'),
  ('Shaken_Futures_2627','Taster Programs','Shaken_Future_Ops'),
  ('Shaken_Futures_2627','Taster Programs','Income_Sources'),
  ('Shaken_Futures_2627','Tondela','Shaken_Future_Ops'),
  ('Shaken_Futures_2627','Tondela','Facilities_and_IT'),
  ('Shaken_Futures_2627','Tondela','Finance_and_Legal'),
  ('Shaken_Futures_2627','Tondela','Income_Sources'),
  ('Ignore','Ignore','Ignore'),
  ('International_2526','General','Finance_and_Legal'),
  ('International_2526','General','Income_Sources'),
  ('International_2627','General','Finance_and_Legal'),
  ('International_2627','General','Income_Sources'),
  ('Professional_Programs_26','AI Dive','Income_Sources'),
  ('Professional_Programs_26','AI Dive','Marketing_and_Admissions'),
  ('Professional_Programs_26','AI Dive','Professional_Programs_Ops'),
  ('Professional_Programs_26','General','Business_Development'),
  ('Professional_Programs_26','General','Communication'),
  ('Professional_Programs_26','General','Data_and_Institution'),
  ('Professional_Programs_26','General','Facilities_and_IT'),
  ('Professional_Programs_26','General','Finance_and_Legal'),
  ('Professional_Programs_26','General','Income_Sources'),
  ('Professional_Programs_26','General','Marketing_and_Admissions'),
  ('Professional_Programs_26','General','People'),
  ('Professional_Programs_26','General','Professional_Programs_Ops'),
  ('Professional_Programs_26','General','Rental_Ops'),
  ('Professional_Programs_26','General Lisboa','Facilities_and_IT'),
  ('Professional_Programs_26','General Lisboa','Rental_Ops'),
  ('Professional_Programs_26','General Porto','Facilities_and_IT'),
  ('Professional_Programs_26','General Porto','Rental_Ops'),
  ('Professional_Programs_26','Step Up','Income_Sources'),
  ('Professional_Programs_26','Step Up','Marketing_and_Admissions'),
  ('Professional_Programs_26','Step Up','Professional_Programs_Ops'),
  ('School_42_26','General','Business_Development'),
  ('School_42_26','General','Communication'),
  ('School_42_26','General','Data_and_Institution'),
  ('School_42_26','General','Executive_Team'),
  ('School_42_26','General','Facilities_and_IT'),
  ('School_42_26','General','Finance_and_Legal'),
  ('School_42_26','General','Income_Sources'),
  ('School_42_26','General','Marketing_and_Admissions'),
  ('School_42_26','General','Merch_Ops'),
  ('School_42_26','General','People'),
  ('School_42_26','General','Rental_Ops'),
  ('School_42_26','General','School_42_Program_Ops'),
  ('School_42_26','General','_42_HQ'),
  ('School_42_26','Lisboa','Facilities_and_IT'),
  ('School_42_26','Lisboa','Income_Sources'),
  ('School_42_26','Lisboa','School_42_Program_Ops'),
  ('School_42_26','Porto','Facilities_and_IT'),
  ('School_42_26','Porto','Income_Sources'),
  ('School_42_26','Porto','School_42_Program_Ops'),
  ('School_42_26','SEA:ME','Business_Development'),
  ('School_42_26','SEA:ME','Communication'),
  ('School_42_26','SEA:ME','Facilities_and_IT'),
  ('School_42_26','SEA:ME','Income_Sources'),
  ('School_42_26','SEA:ME','SEA_ME_Program_Ops'),
  ('Shared_Services_2526','General','Business_Development'),
  ('Shared_Services_2526','General','Communication'),
  ('Shared_Services_2526','General','Data_and_Institution'),
  ('Shared_Services_2526','General','Executive_Team'),
  ('Shared_Services_2526','General','Facilities_and_IT'),
  ('Shared_Services_2526','General','Finance_and_Legal'),
  ('Shared_Services_2526','General','General_Taxes'),
  ('Shared_Services_2526','General','Income_Sources'),
  ('Shared_Services_2526','General','People'),
  ('Shared_Services_26','General','Business_Development'),
  ('Shared_Services_26','General','Communication'),
  ('Shared_Services_26','General','Data_and_Institution'),
  ('Shared_Services_26','General','Executive_Team'),
  ('Shared_Services_26','General','Facilities_and_IT'),
  ('Shared_Services_26','General','Finance_and_Legal'),
  ('Shared_Services_26','General','General_Taxes'),
  ('Shared_Services_26','General','Income_Sources'),
  ('Shared_Services_26','General','People'),
  ('TUMO_2526','Bilbao','Communication'),
  ('TUMO_2526','Bilbao','Facilities_and_IT'),
  ('TUMO_2526','Bilbao','Finance_and_Legal'),
  ('TUMO_2526','Bilbao','Income_Sources'),
  ('TUMO_2526','Bilbao','Marketing_and_Admissions'),
  ('TUMO_2526','Bilbao','People'),
  ('TUMO_2526','Bilbao','TUMO_HQ'),
  ('TUMO_2526','Bilbao','TUMO_Program_Ops'),
  ('TUMO_2526','Coimbra','Communication'),
  ('TUMO_2526','Coimbra','Facilities_and_IT'),
  ('TUMO_2526','Coimbra','Income_Sources'),
  ('TUMO_2526','Coimbra','Marketing_and_Admissions'),
  ('TUMO_2526','Coimbra','TUMO_HQ'),
  ('TUMO_2526','Coimbra','TUMO_Program_Ops'),
  ('TUMO_2526','Espanha','Business_Development'),
  ('TUMO_2526','Espanha','Communication'),
  ('TUMO_2526','Espanha','Data_and_Institution'),
  ('TUMO_2526','Espanha','Finance_and_Legal'),
  ('TUMO_2526','Espanha','General_Taxes'),
  ('TUMO_2526','Espanha','Income_Sources'),
  ('TUMO_2526','Espanha','People'),
  ('TUMO_2526','General','Business_Development'),
  ('TUMO_2526','General','Communication'),
  ('TUMO_2526','General','Data_and_Institution'),
  ('TUMO_2526','General','Executive_Team'),
  ('TUMO_2526','General','Facilities_and_IT'),
  ('TUMO_2526','General','Finance_and_Legal'),
  ('TUMO_2526','General','General_Taxes'),
  ('TUMO_2526','General','Income_Sources'),
  ('TUMO_2526','General','Marketing_and_Admissions'),
  ('TUMO_2526','General','Merch_Ops'),
  ('TUMO_2526','General','People'),
  ('TUMO_2526','General','TUMO_HQ'),
  ('TUMO_2526','General','TUMO_Program_Ops'),
  ('TUMO_2526','Lisboa','Communication'),
  ('TUMO_2526','Lisboa','Facilities_and_IT'),
  ('TUMO_2526','Lisboa','Income_Sources'),
  ('TUMO_2526','Lisboa','Marketing_and_Admissions'),
  ('TUMO_2526','Lisboa','Rental_Ops'),
  ('TUMO_2526','Lisboa','TUMO_HQ'),
  ('TUMO_2526','Lisboa','TUMO_Program_Ops'),
  ('TUMO_2526','Porto','Communication'),
  ('TUMO_2526','Porto','Facilities_and_IT'),
  ('TUMO_2526','Porto','Income_Sources'),
  ('TUMO_2526','Porto','Marketing_and_Admissions'),
  ('TUMO_2526','Porto','Rental_Ops'),
  ('TUMO_2526','Porto','TUMO_HQ'),
  ('TUMO_2526','Porto','TUMO_Program_Ops'),
  ('TUMO_2526','Portugal','Business_Development'),
  ('TUMO_2526','Portugal','Communication'),
  ('TUMO_2526','Portugal','Data_and_Institution'),
  ('TUMO_2526','Portugal','Facilities_and_IT'),
  ('TUMO_2526','Portugal','Finance_and_Legal'),
  ('TUMO_2526','Portugal','General_Taxes'),
  ('TUMO_2526','Portugal','Income_Sources'),
  ('TUMO_2526','Portugal','Marketing_and_Admissions'),
  ('TUMO_2526','Portugal','Merch_Ops'),
  ('TUMO_2526','Portugal','People'),
  ('TUMO_2526','Portugal','TUMO_HQ'),
  ('TUMO_2526','Portugal','TUMO_Program_Ops'),
  ('TUMO_2627','Bilbao','Communication'),
  ('TUMO_2627','Bilbao','Facilities_and_IT'),
  ('TUMO_2627','Bilbao','Finance_and_Legal'),
  ('TUMO_2627','Bilbao','Income_Sources'),
  ('TUMO_2627','Bilbao','Marketing_and_Admissions'),
  ('TUMO_2627','Bilbao','People'),
  ('TUMO_2627','Bilbao','TUMO_HQ'),
  ('TUMO_2627','Bilbao','TUMO_Program_Ops'),
  ('TUMO_2627','Coimbra','Communication'),
  ('TUMO_2627','Coimbra','Facilities_and_IT'),
  ('TUMO_2627','Coimbra','Income_Sources'),
  ('TUMO_2627','Coimbra','Marketing_and_Admissions'),
  ('TUMO_2627','Coimbra','TUMO_HQ'),
  ('TUMO_2627','Coimbra','TUMO_Program_Ops'),
  ('TUMO_2627','Espanha','Business_Development'),
  ('TUMO_2627','Espanha','Communication'),
  ('TUMO_2627','Espanha','Data_and_Institution'),
  ('TUMO_2627','Espanha','Finance_and_Legal'),
  ('TUMO_2627','Espanha','General_Taxes'),
  ('TUMO_2627','Espanha','Income_Sources'),
  ('TUMO_2627','Espanha','People'),
  ('TUMO_2627','General','Business_Development'),
  ('TUMO_2627','General','Communication'),
  ('TUMO_2627','General','Data_and_Institution'),
  ('TUMO_2627','General','Executive_Team'),
  ('TUMO_2627','General','Facilities_and_IT'),
  ('TUMO_2627','General','Finance_and_Legal'),
  ('TUMO_2627','General','General_Taxes'),
  ('TUMO_2627','General','Income_Sources'),
  ('TUMO_2627','General','Marketing_and_Admissions'),
  ('TUMO_2627','General','Merch_Ops'),
  ('TUMO_2627','General','People'),
  ('TUMO_2627','General','TUMO_HQ'),
  ('TUMO_2627','General','TUMO_Program_Ops'),
  ('TUMO_2627','Lisboa','Communication'),
  ('TUMO_2627','Lisboa','Facilities_and_IT'),
  ('TUMO_2627','Lisboa','Income_Sources'),
  ('TUMO_2627','Lisboa','Marketing_and_Admissions'),
  ('TUMO_2627','Lisboa','Rental_Ops'),
  ('TUMO_2627','Lisboa','TUMO_HQ'),
  ('TUMO_2627','Lisboa','TUMO_Program_Ops'),
  ('TUMO_2627','Porto','Communication'),
  ('TUMO_2627','Porto','Facilities_and_IT'),
  ('TUMO_2627','Porto','Income_Sources'),
  ('TUMO_2627','Porto','Marketing_and_Admissions'),
  ('TUMO_2627','Porto','Rental_Ops'),
  ('TUMO_2627','Porto','TUMO_HQ'),
  ('TUMO_2627','Porto','TUMO_Program_Ops'),
  ('TUMO_2627','Portugal','Business_Development'),
  ('TUMO_2627','Portugal','Communication'),
  ('TUMO_2627','Portugal','Data_and_Institution'),
  ('TUMO_2627','Portugal','Facilities_and_IT'),
  ('TUMO_2627','Portugal','Finance_and_Legal'),
  ('TUMO_2627','Portugal','General_Taxes'),
  ('TUMO_2627','Portugal','Income_Sources'),
  ('TUMO_2627','Portugal','Marketing_and_Admissions'),
  ('TUMO_2627','Portugal','Merch_Ops'),
  ('TUMO_2627','Portugal','People'),
  ('TUMO_2627','Portugal','TUMO_HQ'),
  ('TUMO_2627','Portugal','TUMO_Program_Ops'),
  ('TUMO_2627','Setubal','Communication'),
  ('TUMO_2627','Setubal','Facilities_and_IT'),
  ('TUMO_2627','Setubal','Income_Sources'),
  ('TUMO_2627','Setubal','Marketing_and_Admissions'),
  ('TUMO_2627','Setubal','TUMO_HQ'),
  ('TUMO_2627','Setubal','TUMO_Program_Ops');
insert into public.cdg_categoria (cc,categoria) values
  ('Business_Development','Events'),
  ('Business_Development','Partner_Activities'),
  ('Business_Development','Partner_Relations'),
  ('Business_Development','Staff'),
  ('Business_Development','Team_Logistics'),
  ('Business_Development','Team_Management'),
  ('Communication','Content'),
  ('Communication','Events'),
  ('Communication','Open_Donations'),
  ('Communication','Partner_Relations'),
  ('Communication','Press'),
  ('Communication','Staff'),
  ('Communication','Team_Logistics'),
  ('Communication','Team_Management'),
  ('Communication','Team_Training'),
  ('Consulting_Programs_Ops','Consulting_Services'),
  ('Consulting_Programs_Ops','Facilitators'),
  ('Consulting_Programs_Ops','Partner_Relations'),
  ('Consulting_Programs_Ops','Staff'),
  ('Consulting_Programs_Ops','Team_Logistics'),
  ('Consulting_Programs_Ops','Team_Management'),
  ('Data_and_Institution','Data_Management'),
  ('Data_and_Institution','Grants_and_Certifications'),
  ('Data_and_Institution','Partner_Relations'),
  ('Data_and_Institution','Program_Activities'),
  ('Data_and_Institution','Staff'),
  ('Data_and_Institution','Team_Logistics'),
  ('Data_and_Institution','Team_Management'),
  ('Data_and_Institution','Team_Training'),
  ('Executive_Team','Staff'),
  ('External_Programs_Ops','Facilitators'),
  ('External_Programs_Ops','Learning_Hardware'),
  ('External_Programs_Ops','Partner_Relations'),
  ('External_Programs_Ops','Program_Activities'),
  ('External_Programs_Ops','Program_Coordination'),
  ('External_Programs_Ops','Program_Tools'),
  ('External_Programs_Ops','Staff'),
  ('External_Programs_Ops','Team_Logistics'),
  ('External_Programs_Ops','Team_Management'),
  ('External_Programs_Ops','Team_Training'),
  ('Facilities_and_IT','Cleaning_and_Hygiene'),
  ('Facilities_and_IT','IT_Management'),
  ('Facilities_and_IT','Maintenance'),
  ('Facilities_and_IT','Network_and_Connectivity'),
  ('Facilities_and_IT','Office_Management'),
  ('Facilities_and_IT','Safety_Training'),
  ('Facilities_and_IT','Security'),
  ('Facilities_and_IT','Space_Development'),
  ('Facilities_and_IT','Space_Equipment'),
  ('Facilities_and_IT','Space_Resources'),
  ('Facilities_and_IT','Space_Usage'),
  ('Facilities_and_IT','Staff'),
  ('Facilities_and_IT','Team_Logistics'),
  ('Facilities_and_IT','Team_Management'),
  ('Facilities_and_IT','Team_Training'),
  ('Finance_and_Legal','Accounting_and_Audit'),
  ('Finance_and_Legal','Contract_Management'),
  ('Finance_and_Legal','Credits_and_Roundings'),
  ('Finance_and_Legal','Financial_Management'),
  ('Finance_and_Legal','Legal_and_Regulatory'),
  ('Finance_and_Legal','Partner_Relations'),
  ('Finance_and_Legal','Risk_and_Compliance'),
  ('Finance_and_Legal','Staff'),
  ('Finance_and_Legal','Team_Logistics'),
  ('Finance_and_Legal','Team_Management'),
  ('Finance_and_Legal','Team_Training'),
  ('General_Taxes','Taxes'),
  ('Ignore','Ignore'),
  ('Income_Sources','Client_Services'),
  ('Income_Sources','Donations'),
  ('Income_Sources','Financial_Income'),
  ('Income_Sources','Group_Contributions'),
  ('Income_Sources','Items_Sold'),
  ('Income_Sources','Subsidies_and_Grants'),
  ('Marketing_and_Admissions','Admission_Activities'),
  ('Marketing_and_Admissions','Content'),
  ('Marketing_and_Admissions','Events'),
  ('Marketing_and_Admissions','IRS_Campaign'),
  ('Marketing_and_Admissions','Online_Campaigns'),
  ('Marketing_and_Admissions','Promotion_Activities'),
  ('Marketing_and_Admissions','Staff'),
  ('Marketing_and_Admissions','Team_Logistics'),
  ('Marketing_and_Admissions','Team_Management'),
  ('Marketing_and_Admissions','Team_Training'),
  ('Merch_Ops','Merch_Logistics'),
  ('People','Engagement'),
  ('People','Grants_and_Certifications'),
  ('People','HR_Management'),
  ('People','Recruitment'),
  ('People','Retreat'),
  ('People','Staff'),
  ('People','Team_Logistics'),
  ('People','Team_Management'),
  ('People','Team_Training'),
  ('Professional_Programs_Ops','Facilitators'),
  ('Professional_Programs_Ops','Partner_Relations'),
  ('Professional_Programs_Ops','Program_Activities'),
  ('Professional_Programs_Ops','Program_Tools'),
  ('Professional_Programs_Ops','Programs_Facilitator'),
  ('Professional_Programs_Ops','Programs_Trainee'),
  ('Professional_Programs_Ops','Staff'),
  ('Professional_Programs_Ops','Team_Logistics'),
  ('Professional_Programs_Ops','Team_Management'),
  ('Professional_Programs_Ops','Team_Training'),
  ('Professional_Programs_Ops','Training_Programs_Support'),
  ('Rental_Ops','Rental_Logistics'),
  ('SEA_ME_Program_Ops','Kick_Offs'),
  ('SEA_ME_Program_Ops','Partner_Relations'),
  ('SEA_ME_Program_Ops','Program_Activities'),
  ('SEA_ME_Program_Ops','Scholarships'),
  ('SEA_ME_Program_Ops','Staff'),
  ('SEA_ME_Program_Ops','Team_Logistics'),
  ('School_42_Program_Ops','Alumni'),
  ('School_42_Program_Ops','Events'),
  ('School_42_Program_Ops','International_Visits'),
  ('School_42_Program_Ops','Kick_Offs'),
  ('School_42_Program_Ops','Learning_Hardware'),
  ('School_42_Program_Ops','Partner_Relations'),
  ('School_42_Program_Ops','Piscines'),
  ('School_42_Program_Ops','Program_Activities'),
  ('School_42_Program_Ops','Program_Tools'),
  ('School_42_Program_Ops','Staff'),
  ('School_42_Program_Ops','Team_Logistics'),
  ('School_42_Program_Ops','Team_Management'),
  ('School_42_Program_Ops','Team_Training'),
  ('TUMO_HQ','Network_Meeting'),
  ('TUMO_HQ','Partner_Relations'),
  ('TUMO_HQ','Royalties'),
  ('TUMO_Program_Ops','Alt_July'),
  ('TUMO_Program_Ops','Ed_Staff_Management'),
  ('TUMO_Program_Ops','Ed_Staff_Training'),
  ('TUMO_Program_Ops','Learning_Coaches'),
  ('TUMO_Program_Ops','Learning_Hardware'),
  ('TUMO_Program_Ops','Partner_Relations'),
  ('TUMO_Program_Ops','Program_Activities'),
  ('TUMO_Program_Ops','Program_Tools'),
  ('TUMO_Program_Ops','Staff'),
  ('TUMO_Program_Ops','Team_Logistics'),
  ('TUMO_Program_Ops','Team_Management'),
  ('TUMO_Program_Ops','Team_Training'),
  ('TUMO_Program_Ops','Workshop_Leaders'),
  ('_42_HQ','Network_Audit'),
  ('_42_HQ','Network_Meeting'),
  ('_42_HQ','Royalties'),
  ('Shaken_Future_Ops','Facilitators'),
  ('Shaken_Future_Ops','Learning_Hardware'),
  ('Shaken_Future_Ops','Partner_Relations'),
  ('Shaken_Future_Ops','Program_Activities'),
  ('Shaken_Future_Ops','Program_Coordination'),
  ('Shaken_Future_Ops','Program_Tools'),
  ('Shaken_Future_Ops','Staff'),
  ('Shaken_Future_Ops','Team_Logistics'),
  ('Shaken_Future_Ops','Team_Management'),
  ('Shaken_Future_Ops','Team_Training');
insert into public.cdg_detalhe (categoria,detalhe) values
  ('Accounting_and_Audit','Accounting'),
  ('Accounting_and_Audit','Auditing'),
  ('Admission_Activities','Admissions Hours'),
  ('Admission_Activities','Comms Channels'),
  ('Admission_Activities','Form Tool'),
  ('Admission_Activities','Other Tools'),
  ('Admission_Activities','Travel & Represent'),
  ('Admission_Activities','Website'),
  ('Alt_July','Coffee and Snacks'),
  ('Alt_July','Guest Expenses'),
  ('Alt_July','LC Alt-July Hours'),
  ('Alt_July','Learning Materials'),
  ('Alt_July','Travel & Represent'),
  ('Alt_July','WSL Alt-July Hours'),
  ('Alumni','Other Expenses'),
  ('Alumni','Student Items'),
  ('Alumni','Travel & Represent'),
  ('Cleaning_and_Hygiene','Cleaning Services'),
  ('Cleaning_and_Hygiene','Cleaning Supplies'),
  ('Cleaning_and_Hygiene','Hygiene Services'),
  ('Cleaning_and_Hygiene','Pest Control'),
  ('Cleaning_and_Hygiene','Specialized Cleaning'),
  ('Client_Services','Events Fees'),
  ('Client_Services','Job Fair'),
  ('Client_Services','Other Client Services'),
  ('Client_Services','Programs'),
  ('Client_Services','Rentals'),
  ('Consulting_Services','External Consultant'),
  ('Consulting_Services','Travel & Represent'),
  ('Content','Campaign Creativity'),
  ('Content','Institutional Materials'),
  ('Content','Photo and Video'),
  ('Content','Website'),
  ('Contract_Management','Digital Signature'),
  ('Contract_Management','Digital Signing Tools'),
  ('Credits_and_Roundings','Credits & Roundings'),
  ('Data_Management','Database Tool'),
  ('Data_Management','Form Tool'),
  ('Donations','Heart of Gold Fellowship'),
  ('Donations','IRS'),
  ('Donations','Open Donations'),
  ('Donations','Partner Donations'),
  ('Ed_Staff_Management','Laundry Services'),
  ('Ed_Staff_Management','Team Gear'),
  ('Ed_Staff_Management','Travel & Represent'),
  ('Ed_Staff_Management','Welcome Kits'),
  ('Ed_Staff_Training','Armenia Training Fees'),
  ('Ed_Staff_Training','Guests'),
  ('Ed_Staff_Training','LC Training Hours'),
  ('Ed_Staff_Training','Travel & Represent'),
  ('Ed_Staff_Training','WSL Training Hours'),
  ('Engagement','Coffee and Snacks'),
  ('Engagement','Staff Amenities'),
  ('Engagement','Travel & Represent'),
  ('Engagement','Welcome Kits'),
  ('Events','Ads'),
  ('Events','Cleaning Services'),
  ('Events','Coffee and Snacks'),
  ('Events','Event Insurance'),
  ('Events','LC Promotion Hours'),
  ('Events','Other Expenses'),
  ('Events','Photo and Video'),
  ('Events','Promotion Materials'),
  ('Events','Travel & Represent'),
  ('Events','WSL Promotion Hours'),
  ('Facilitators','LC External Program Hours'),
  ('Facilitators','LC External Program Training'),
  ('Facilitators','Other Facilitators'),
  ('Facilitators','WSL External Program Hours'),
  ('Facilitators','WSL External Program Training'),
  ('Financial_Income','Interest Income'),
  ('Financial_Management','AI Invoice Reader'),
  ('Financial_Management','Bank Commissions'),
  ('Financial_Management','ERP License'),
  ('Financial_Management','ERP Server'),
  ('Financial_Management','ERP Support Hours'),
  ('Financial_Management','Expenses Tool'),
  ('Financial_Management','Purchase Management'),
  ('Financial_Management','Report Tool'),
  ('Financial_Management','Tool Development'),
  ('Grants_and_Certifications','Certification Fees'),
  ('Grants_and_Certifications','Grant Filing Support'),
  ('Grants_and_Certifications','Grants Compliance'),
  ('Grants_and_Certifications','Grants Tools'),
  ('Grants_and_Certifications','Signage'),
  ('HR_Management','Flex Benefits Tool'),
  ('HR_Management','HR Software'),
  ('IRS_Campaign','Ads'),
  ('IRS_Campaign','Promotion Materials'),
  ('IT_Management','Cybersecurity Support'),
  ('IT_Management','Device Management Tool'),
  ('IT_Management','IT Support Services'),
  ('IT_Management','Online Domains'),
  ('IT_Management','Online Server'),
  ('IT_Management','Password Management Tool'),
  ('IT_Management','SSL & Identity Management'),
  ('IT_Management','Setup Services'),
  ('IT_Management','Streaming Management Tool'),
  ('Ignore','Ignore'),
  ('International_Visits','Travel & Represent'),
  ('Items_Sold','Merchandising'),
  ('Items_Sold','Payment Fees'),
  ('Items_Sold','Sales'),
  ('Kick_Offs','Catering'),
  ('Kick_Offs','Coffee and Snacks'),
  ('Kick_Offs','Other Expenses'),
  ('Kick_Offs','Photo and Video'),
  ('Kick_Offs','Student Items'),
  ('Kick_Offs','Travel & Represent'),
  ('Learning_Coaches','Contract Terminations'),
  ('Learning_Coaches','LC Infodesk Hours'),
  ('Learning_Coaches','Program Hours'),
  ('Learning_Coaches','Replacement Hours'),
  ('Learning_Hardware','Chromebooks'),
  ('Learning_Hardware','Chromebooks Renting'),
  ('Learning_Hardware','Computers Renting'),
  ('Learning_Hardware','Design Tablets'),
  ('Learning_Hardware','Hardware Repairs'),
  ('Learning_Hardware','Music Equipment'),
  ('Learning_Hardware','Other Equipment'),
  ('Learning_Hardware','Photo/ Cine Equipment'),
  ('Learning_Hardware','Robotics Equipment'),
  ('Learning_Hardware','Supporting Equipment'),
  ('Learning_Hardware','iMacs'),
  ('Legal_and_Regulatory','Fiscal Support'),
  ('Legal_and_Regulatory','Legal Support'),
  ('Legal_and_Regulatory','Regulatory Fees'),
  ('Maintenance','Consumables'),
  ('Maintenance','HVAC Repairs'),
  ('Maintenance','Preventive Defibrillator'),
  ('Maintenance','Preventive Electric'),
  ('Maintenance','Preventive Elevators'),
  ('Maintenance','Preventive Fire Safety'),
  ('Maintenance','Preventive HVAC'),
  ('Maintenance','Space Repairs'),
  ('Merch_Logistics','Merchandising'),
  ('Merch_Logistics','Payment Fees'),
  ('Network_Audit','Travel & Represent'),
  ('Network_Meeting','Travel & Represent'),
  ('Network_and_Connectivity','Internet Services'),
  ('Network_and_Connectivity','Network Maintenance'),
  ('Network_and_Connectivity','OS Server Licenses'),
  ('Network_and_Connectivity','OS Server Maintenance'),
  ('Network_and_Connectivity','Switches and AP Licenses'),
  ('Network_and_Connectivity','VMWare Licenses'),
  ('Office_Management','Coffee and Snacks'),
  ('Office_Management','Courier & Postal'),
  ('Office_Management','First Aid Supplies'),
  ('Office_Management','Prints and Stationery'),
  ('Online_Campaigns','Ads'),
  ('Online_Campaigns','Mail Marketing'),
  ('Online_Campaigns','Performance Marketing Services'),
  ('Open_Donations','Donation Tool'),
  ('Open_Donations','Payment Fees'),
  ('Open_Donations','Signage'),
  ('Partner_Activities','Coffee and Snacks'),
  ('Partner_Activities','Guest Expenses'),
  ('Partner_Activities','Guests'),
  ('Partner_Activities','LC Hub Hours'),
  ('Partner_Activities','Other Expenses'),
  ('Partner_Activities','Student Comp'),
  ('Partner_Activities','Travel & Represent'),
  ('Partner_Activities','WSL Hub Hours'),
  ('Partner_Relations','CRM'),
  ('Partner_Relations','Coffee and Snacks'),
  ('Partner_Relations','Institutional Reports'),
  ('Partner_Relations','Partner Gifts'),
  ('Partner_Relations','Signage'),
  ('Partner_Relations','Travel & Represent'),
  ('Piscines','Coffee and Snacks'),
  ('Piscines','Lifeguards'),
  ('Piscines','Student Items'),
  ('Piscines','Team Gear'),
  ('Piscines','Travel & Represent'),
  ('Press','Clipping'),
  ('Program_Activities','Coffee and Snacks'),
  ('Program_Activities','Guests'),
  ('Program_Activities','LC Hub Hours'),
  ('Program_Activities','Learning Materials'),
  ('Program_Activities','Other Program Activities'),
  ('Program_Activities','PCs Renting'),
  ('Program_Activities','Student Comp'),
  ('Program_Activities','Student Items'),
  ('Program_Activities','Travel & Represent'),
  ('Program_Activities','Venue Rental'),
  ('Program_Activities','WSL Hub Hours'),
  ('Program_Coordination','Travel & Represent'),
  ('Program_Tools','3D Modelling Software'),
  ('Program_Tools','AI Tools'),
  ('Program_Tools','Animation Software'),
  ('Program_Tools','Creative Software'),
  ('Program_Tools','DGERT Certificates'),
  ('Program_Tools','Form Tool'),
  ('Program_Tools','Learning Management System'),
  ('Program_Tools','Music Prod Software'),
  ('Program_Tools','Payment Fees'),
  ('Program_Tools','Quiz Tool'),
  ('Program_Tools','Scheduling Tool'),
  ('Program_Tools','Student Accounts'),
  ('Program_Tools','Student Selection Tool'),
  ('Program_Tools','Tool Development'),
  ('Program_Tools','Video Conferencing Tool'),
  ('Program_Tools','Video Generator Tool'),
  ('Programs_Facilitator','Base Compensation'),
  ('Programs_Facilitator','Contract Terminations'),
  ('Programs_Facilitator','Prizes'),
  ('Programs_Trainee','Base Compensation'),
  ('Programs_Trainee','Contract Terminations'),
  ('Programs_Trainee','Prizes'),
  ('Promotion_Activities','Coffee and Snacks'),
  ('Promotion_Activities','LC Promotion Hours'),
  ('Promotion_Activities','Other Expenses'),
  ('Promotion_Activities','Promotion Materials'),
  ('Promotion_Activities','Registration Fees'),
  ('Promotion_Activities','Signage'),
  ('Promotion_Activities','Student Ambassadors'),
  ('Promotion_Activities','Student Comp'),
  ('Promotion_Activities','Travel & Represent'),
  ('Promotion_Activities','WSL Promotion Hours'),
  ('Recruitment','Ads'),
  ('Recruitment','Coffee and Snacks'),
  ('Recruitment','LC Recruitment Events'),
  ('Recruitment','Promotion Materials'),
  ('Recruitment','Recruitment Management Tool'),
  ('Recruitment','Recruitment Sourcing Tool'),
  ('Recruitment','Registration Fees'),
  ('Recruitment','Travel & Represent'),
  ('Recruitment','WSL Recruitment Events'),
  ('Rental_Logistics','Cleaning Services'),
  ('Rental_Logistics','Coffee and Snacks'),
  ('Rental_Logistics','Event Insurance'),
  ('Rental_Logistics','Other Expenses'),
  ('Rental_Logistics','Staff Overtime'),
  ('Rental_Logistics','Travel & Represent'),
  ('Retreat','Other Expenses'),
  ('Retreat','Travel & Represent'),
  ('Risk_and_Compliance','Admissions Consults'),
  ('Risk_and_Compliance','Cyber Insurance'),
  ('Risk_and_Compliance','Facilities Insurance'),
  ('Risk_and_Compliance','General Liability Insurance'),
  ('Risk_and_Compliance','Occ. Health & Safety'),
  ('Risk_and_Compliance','Professional Insurance'),
  ('Risk_and_Compliance','Student Insurance'),
  ('Risk_and_Compliance','Travel Insurance'),
  ('Risk_and_Compliance','Work Accidents Insurance'),
  ('Royalties','Royalties'),
  ('Safety_Training','Defibrillator Training'),
  ('Safety_Training','Fire Combat Training'),
  ('Safety_Training','Fire Drill Training'),
  ('Safety_Training','First Aid Training'),
  ('Safety_Training','Safety Measures Training'),
  ('Scholarships','Scholarships'),
  ('Security','Access Cards'),
  ('Security','Access Management Support'),
  ('Security','CCTV Support'),
  ('Security','On-Site Security'),
  ('Security','Remote Surveillance'),
  ('Space_Development','Access Management Equipment'),
  ('Space_Development','CCTV Equipment'),
  ('Space_Development','Construction'),
  ('Space_Development','Moving Expenses'),
  ('Space_Development','Tech Infrastructure'),
  ('Space_Development','Technical Studies'),
  ('Space_Development','Travel & Represent'),
  ('Space_Equipment','Appliances'),
  ('Space_Equipment','Furniture'),
  ('Space_Equipment','Kitchen Material'),
  ('Space_Equipment','Signage'),
  ('Space_Equipment','Audiovisuals'),
  ('Space_Equipment','Tools and Electricals'),
  ('Space_Resources','Defibrillator Rental'),
  ('Space_Resources','Filtered Water'),
  ('Space_Resources','Gardening'),
  ('Space_Resources','Parking'),
  ('Space_Resources','Seasonal Decorations'),
  ('Space_Usage','Condominium'),
  ('Space_Usage','Electricity'),
  ('Space_Usage','Rent'),
  ('Space_Usage','Sub-Leasing'),
  ('Space_Usage','Water'),
  ('Staff','Base Compensation'),
  ('Staff','Car Renting'),
  ('Staff','Contract Terminations'),
  ('Staff','Health Insurance'),
  ('Staff','Prizes'),
  ('Subsidies_and_Grants','Employment Subsidies'),
  ('Subsidies_and_Grants','Grants & Prizes'),
  ('Taxes','Contracting Entity SS'),
  ('Taxes','Fines'),
  ('Taxes','Income Tax'),
  ('Taxes','VAT Differences'),
  ('Team_Logistics','AI Tools'),
  ('Team_Logistics','Productivity Tools'),
  ('Team_Logistics','Staff Equipment'),
  ('Team_Logistics','Telephone Services'),
  ('Team_Logistics','Travel & Represent'),
  ('Team_Management','Staff Amenities'),
  ('Team_Management','Travel & Represent'),
  ('Team_Training','Other Training Costs'),
  ('Team_Training','Travel & Represent'),
  ('Training_Programs_Support','Base Compensation'),
  ('Training_Programs_Support','Contract Terminations'),
  ('Training_Programs_Support','Prizes'),
  ('Workshop_Leaders','Contract Terminations'),
  ('Workshop_Leaders','Creation/ Prep Hours'),
  ('Workshop_Leaders','Live Grading Hours'),
  ('Workshop_Leaders','Maintenance Hours'),
  ('Workshop_Leaders','Program Hours'),
  ('Workshop_Leaders','Replacement Hours');
insert into public.cdg_tipo (detalhe,tipo) values
  ('3D Modelling Software','OPEX'),
  ('AC Rental','OPEX'),
  ('AI Invoice Reader','OPEX'),
  ('AI Tools','OPEX'),
  ('Access Cards','OPEX'),
  ('Access Management Equipment','CAPEX'),
  ('Access Management Support','OPEX'),
  ('Accounting','OPEX'),
  ('Admissions Consults','OPEX'),
  ('Admissions Hours','OPEX'),
  ('Ads','OPEX'),
  ('Animation Software','OPEX'),
  ('Appliances','CAPEX'),
  ('Armenia Training Fees','OPEX'),
  ('Auditing','OPEX'),
  ('Bank Commissions','OPEX'),
  ('Base Compensation','OPEX'),
  ('CCTV Equipment','CAPEX'),
  ('CCTV Support','OPEX'),
  ('CRM','OPEX'),
  ('Campaign Creativity','OPEX'),
  ('Car Renting','OPEX'),
  ('Catering','OPEX'),
  ('Certification Fees','OPEX'),
  ('Chromebooks','CAPEX'),
  ('Chromebooks Renting','CAPEX'),
  ('Cleaning Services','OPEX'),
  ('Cleaning Supplies','OPEX'),
  ('Clipping','OPEX'),
  ('Coffee and Snacks','OPEX'),
  ('Collaboration Tools','OPEX'),
  ('Comms Channels','OPEX'),
  ('Computers Renting','CAPEX'),
  ('Condominium','OPEX'),
  ('Construction','CAPEX'),
  ('Consumables','OPEX'),
  ('Contract Terminations','OPEX'),
  ('Contracting Entity SS','OPEX'),
  ('Courier & Postal','OPEX'),
  ('Creation/ Prep Hours','OPEX'),
  ('Creative Software','OPEX'),
  ('Credits & Roundings','OPEX'),
  ('Cyber Insurance','OPEX'),
  ('Cybersecurity Support','OPEX'),
  ('DGERT Certificates','OPEX'),
  ('Database Tool','OPEX'),
  ('Deep Cleaning','OPEX'),
  ('Defibrillator Rental','OPEX'),
  ('Defibrillator Training','OPEX'),
  ('Design Tablets','CAPEX'),
  ('Development','OPEX'),
  ('Device Management Tool','OPEX'),
  ('Digital Signature','OPEX'),
  ('Digital Signing Tools','OPEX'),
  ('Donation Tool','OPEX'),
  ('ERP License','OPEX'),
  ('ERP Server','OPEX'),
  ('ERP Support Hours','OPEX'),
  ('Ed Staff Meetings','OPEX'),
  ('Electricity','OPEX'),
  ('Employment Subsidies','Revenue'),
  ('End of Year Gathering','OPEX'),
  ('Event Insurance','OPEX'),
  ('Events','OPEX'),
  ('Events Fees','Revenue'),
  ('Events Participation Fees','Revenue'),
  ('Expenses Tool','OPEX'),
  ('External Consultant','OPEX'),
  ('Facilities Insurance','OPEX'),
  ('Filtered Water','OPEX'),
  ('Fines','OPEX'),
  ('Fire Combat Training','OPEX'),
  ('Fire Drill Training','OPEX'),
  ('First Aid Supplies','OPEX'),
  ('First Aid Training','OPEX'),
  ('Fiscal Support','OPEX'),
  ('Flex Benefits Tool','OPEX'),
  ('Form Tool','OPEX'),
  ('Furniture','CAPEX'),
  ('Garbage Disposal','OPEX'),
  ('Gardening','OPEX'),
  ('General Liability Insurance','OPEX'),
  ('Grant Filing Support','OPEX'),
  ('Grants & Prizes','Revenue'),
  ('Grants Compliance','OPEX'),
  ('Grants Tools','OPEX'),
  ('Guest Expenses','OPEX'),
  ('Guests','OPEX'),
  ('HR Software','OPEX'),
  ('HVAC Rental','OPEX'),
  ('HVAC Repairs','OPEX'),
  ('Hardware Repairs','OPEX'),
  ('Health Insurance','OPEX'),
  ('Heart of Gold Fellowship','Revenue'),
  ('Hygiene Services','OPEX'),
  ('IRS','Revenue'),
  ('IT Support Services','OPEX'),
  ('IT Ticketing Tool','OPEX'),
  ('Ignore','Ignore'),
  ('Income Tax','OPEX'),
  ('Institutional Materials','OPEX'),
  ('Institutional Reports','OPEX'),
  ('Intercenter Shadowing','OPEX'),
  ('Interest Income','Revenue'),
  ('Internet Services','OPEX'),
  ('Job Fair','Revenue'),
  ('Kitchen Material','CAPEX'),
  ('LC Alt-July Hours','OPEX'),
  ('LC Assessment Events','OPEX'),
  ('LC External Program Hours','OPEX'),
  ('LC External Program Training','OPEX'),
  ('LC Hub Hours','OPEX'),
  ('LC Infodesk Hours','OPEX'),
  ('LC Promotion Hours','OPEX'),
  ('LC Recruitment Events','OPEX'),
  ('LC Training Hours','OPEX'),
  ('Laundry Services','OPEX'),
  ('Learning Management System','OPEX'),
  ('Learning Materials','OPEX'),
  ('Legal Support','OPEX'),
  ('Lifeguards','OPEX'),
  ('Live Grading Hours','OPEX'),
  ('Mail Marketing','OPEX'),
  ('Maintenance Hours','OPEX'),
  ('Merchandising','OPEX'),
  ('Moving Expenses','OPEX'),
  ('Music Equipment','CAPEX'),
  ('Music Prod Software','OPEX'),
  ('Network Maintenance','OPEX'),
  ('OS Server Licenses','OPEX'),
  ('OS Server Maintenance','OPEX'),
  ('Occ. Health & Safety','OPEX'),
  ('On-Site Security','OPEX'),
  ('Online Domains','OPEX'),
  ('Online Server','OPEX'),
  ('Open Donations','Revenue'),
  ('Other Client Services','Revenue'),
  ('Other Equipment','CAPEX'),
  ('Other Expenses','OPEX'),
  ('Other Facilitators','OPEX'),
  ('Other Program Activities','OPEX'),
  ('Other Tools','OPEX'),
  ('Other Training Costs','OPEX'),
  ('PCs Renting','OPEX'),
  ('Parking','OPEX'),
  ('Partner Donations','Revenue'),
  ('Partner Gifts','OPEX'),
  ('Password Management Tool','OPEX'),
  ('Payment Fees','OPEX'),
  ('Performance Marketing Services','OPEX'),
  ('Pest Control','OPEX'),
  ('Photo and Video','OPEX'),
  ('Photo/ Cine Equipment','CAPEX'),
  ('Preventive Defibrillator','OPEX'),
  ('Preventive Electric','OPEX'),
  ('Preventive Elevators','OPEX'),
  ('Preventive Fire Safety','OPEX'),
  ('Preventive HVAC','OPEX'),
  ('Prints and Stationery','OPEX'),
  ('Prizes','OPEX'),
  ('Productivity Tools','OPEX'),
  ('Professional Activity Insurance','OPEX'),
  ('Program Hours','OPEX'),
  ('Programs','Revenue'),
  ('Promotion Materials','OPEX'),
  ('Purchase Management','OPEX'),
  ('Quiz Tool','OPEX'),
  ('Recruitment Management Tool','OPEX'),
  ('Recruitment Sourcing Tool','OPEX'),
  ('Registration Fees','OPEX'),
  ('Regulatory Fees','OPEX'),
  ('Remote Surveillance','OPEX'),
  ('Rent','OPEX'),
  ('Rentals','Revenue'),
  ('Replacement Hours','OPEX'),
  ('Report Tool','OPEX'),
  ('Robotics Equipment','CAPEX'),
  ('Royalties','OPEX'),
  ('SSL & Identity Management','OPEX'),
  ('Safety Measures Training','OPEX'),
  ('Sales','Revenue'),
  ('Scheduling Tool','OPEX'),
  ('Scholarships','OPEX'),
  ('Seasonal Decorations','OPEX'),
  ('Security Consumables','OPEX'),
  ('Setup Services','OPEX'),
  ('Signage','CAPEX'),
  ('Space Repairs','OPEX'),
  ('Space Upkeep','OPEX'),
  ('Specialized Cleaning','OPEX'),
  ('Staff Amenities','OPEX'),
  ('Staff Equip Purchases','CAPEX'),
  ('Staff Equip Renting','CAPEX'),
  ('Staff Equipment','CAPEX'),
  ('Staff Overtime','OPEX'),
  ('Streaming Management Tool','OPEX'),
  ('Student Accounts','OPEX'),
  ('Student Ambassadors','OPEX'),
  ('Student Clubs','OPEX'),
  ('Student Comp','OPEX'),
  ('Student Events','OPEX'),
  ('Student Insurance','OPEX'),
  ('Student Items','OPEX'),
  ('Student Selection Tool','OPEX'),
  ('Student Union','OPEX'),
  ('Sub-Leasing','OPEX'),
  ('Supporting Equipment','CAPEX'),
  ('Switches and AP Licenses','OPEX'),
  ('Audiovisuals','CAPEX'),
  ('Team Gear','OPEX'),
  ('Tech Infrastructure','CAPEX'),
  ('Technical Studies','CAPEX'),
  ('Telephone Services','OPEX'),
  ('Tool Development','OPEX'),
  ('Tools and Electricals','CAPEX'),
  ('Training','OPEX'),
  ('Travel & Represent','OPEX'),
  ('Travel Insurance','OPEX'),
  ('VAT Differences','OPEX'),
  ('VMWare Licenses','OPEX'),
  ('Venue Rental','OPEX'),
  ('Video Conferencing Tool','OPEX'),
  ('Video Generator Tool','OPEX'),
  ('WSL Alt-July Hours','OPEX'),
  ('WSL External Program Hours','OPEX'),
  ('WSL External Program Training','OPEX'),
  ('WSL Hub Hours','OPEX'),
  ('WSL Promotion Hours','OPEX'),
  ('WSL Recruitment Events','OPEX'),
  ('WSL Training Hours','OPEX'),
  ('Wall of Fame','OPEX'),
  ('Water','OPEX'),
  ('Website','OPEX'),
  ('Welcome Kits','OPEX'),
  ('Work Accidents Insurance','OPEX'),
  ('iMacs','CAPEX');
insert into public.cdg_projeto (nome) values
  ('Acelerador - Évora'),
  ('Assessment Center Bilbao'),
  ('Axians'),
  ('BC Coimbra'),
  ('BC Lisboa'),
  ('BC Porto'),
  ('BC UKVI and Life Skills'),
  ('BPI'),
  ('Banco de Portugal'),
  ('British Council'),
  ('CF Critical Software'),
  ('CIP Lisboa'),
  ('CIP Porto'),
  ('Career Portal'),
  ('Coimbra'),
  ('Connect & Grow Nov 2025'),
  ('Convergence Week'),
  ('DILLS'),
  ('Discovery - Santander - 1'),
  ('Discovery Week Ribadouro'),
  ('E&Y'),
  ('End of Year Gathering'),
  ('Esporão'),
  ('Experience AI - Professores'),
  ('Galp'),
  ('General'),
  ('HST'),
  ('Iberis'),
  ('Inauguração TUMO Porto'),
  ('Jeronimo Martins'),
  ('Job Fair 2026'),
  ('Leroy Merlin'),
  ('Lisboa'),
  ('Park - Discovery Mornings'),
  ('Piaui Barcelona 2026'),
  ('Piaui Berlim 2025'),
  ('Piaui Berlim 2026'),
  ('Porto'),
  ('Projeto Europeu'),
  ('Ribadouro - Discovery Week - 2'),
  ('TASIS - After School - 1'),
  ('Tech & Arts'),
  ('Tech and Arts'),
  ('Tourism Conference IPBN'),
  ('Tribeca'),
  ('Trilho - Tondela'),
  ('ULIS - UBB Program'),
  ('Visuonary Ventures'),
  ('Évora - Acelerador'),
  ('Évora - Bootcamps');

commit;
